[Add] No internet connection UI for template 5
Ordering-Inc/Ordering-UI pull request #1001
Opened 2022-04-08 15:59 UTC by dreamsky2020

STORY: https://app.asana.com/0/1198717964402573/1202072110042662
Demo: https://d.pr/i/v9OeQ7

2022-04-08 20:12 UTC, quirozcarlos requested changes

2022-04-08 20:12 UTC, quirozcarlos commented on src/themes/five/src/components/NotNetworkConnectivity/index.js
> +      {props.beforeElements?.map((BeforeElement, i) => (
We don't need this validations anymore, please delete it

2022-04-11 18:47 UTC, carlosq-ordering approved these changes

2022-04-11 18:48 UTC, quirozcarlos approved these changes

2022-04-11 18:48 UTC, merged