Feedback auto scroll next option
Ordering-Inc/Ordering-UI pull request #1044
Opened 2022-04-30 08:47 UTC by mingxue-ordering

Story : https://app.asana.com/0/home/1200550251832815/1202175897616918
Demo :  https://d.pr/v/QVkVYg

2022-04-30 14:19 UTC, carlosq-ordering requested changes
I think you should keep scrolling with the comment

2022-04-30 14:19 UTC, carlosq-ordering commented on src/themes/five/src/components/ProductForm/index.js
> +    myElement.scrollIntoView(true)
add validation in case it's  `myElement` undefined

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-04-30 14:19 UTC, carlosq-ordering commented on src/themes/five/src/components/ProductForm/index.js
> +    productContainer.scrollTop -= 100
add validation in case it's myElement undefined

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-05-02 19:03 UTC, mingxue-ordering commented
Demo: https://d.pr/v/QVkVYg

2022-05-02 19:11 UTC, mingxue-ordering commented
Demo:  https://d.pr/v/m2B6Xv

2022-05-02 20:11 UTC, carlosq-ordering approved these changes

2022-05-02 20:11 UTC, merged