[ADD] opt login tab
Ordering-Inc/Ordering-UI pull request #1124
Opened 2022-06-10 23:29 UTC by YisusJe

2022-06-13 13:10 UTC, carlosq-ordering requested changes

2022-06-13 13:10 UTC, carlosq-ordering commented on src/themes/five/src/components/LoginForm/index.js
> +                      placeholder='000000'
Use theme color

2022-06-17 02:50 UTC, YisusJe commented on src/themes/five/src/components/LoginForm/index.js
> +                      placeholder='000000'
that is only a placeholder

2022-06-17 12:35 UTC, carlosq-ordering requested changes

2022-06-17 12:35 UTC, carlosq-ordering commented on src/themes/five/src/components/LoginForm/index.js
> +                      placeholder='000000'
Use theme color

2022-06-17 23:51 UTC, carlosq-ordering requested changes

2022-06-17 23:51 UTC, carlosq-ordering commented on src/themes/five/src/components/LoginForm/index.js
> +  const otpPlaceholder = [...Array(numOtpInputs)].map((b, i) => i - i).join('')
use `fill` JS method

2022-06-18 16:22 UTC, carlosq-ordering approved these changes

2022-06-18 16:22 UTC, merged