add style for button in singleProductCart
Ordering-Inc/Ordering-UI pull request #1281
Opened 2022-09-07 06:38 UTC by mingxue-ordering

Story: https://app.asana.com/0/home/1200550251832815/1202925008619977
Demo: https://d.pr/v/clDmz6

2022-09-07 14:18 UTC, carlosq-ordering requested changes

2022-09-07 14:18 UTC, carlosq-ordering commented on src/themes/five/src/components/SingleProductCard/index.js
> +        hasAddButt={!useCustomFunctionality && typeof hideAddButton !== 'undefined' && !hideAddButton && !isSkeleton}
Please rename this prop `hasAddButt` appropriately (`isHideAddButton` for example), and fix the condition, you're doing unnecesaries validations for example `typeof hideAddButton !== 'undefined'`

2022-09-07 17:37 UTC, mingxue-ordering commented
I've just renamed hasAddButt as isHasAddButt

2022-09-08 00:38 UTC, carlosq-ordering approved these changes

2022-09-08 00:38 UTC, merged