business logo validation
Ordering-Inc/Ordering-UI pull request #1286
Opened 2022-09-07 20:05 UTC by mingxue-ordering

Story: https://app.asana.com/0/home/1200550251832815/1202929379818005
Demo: https://d.pr/v/AIcjLp

2022-09-08 00:39 UTC, carlosq-ordering requested changes

2022-09-08 00:39 UTC, carlosq-ordering commented on src/themes/five/src/components/OrderDetails/index.js
> +    return new Promise((resolve, reject) => {
This code can be refactored

2022-09-08 01:04 UTC, mingxue-ordering commented on src/themes/five/src/components/OrderDetails/index.js
> +    return new Promise((resolve, reject) => {
I've updated code

2022-09-09 14:50 UTC, carlosq-ordering approved these changes

2022-09-09 14:50 UTC, merged