bug recaptcha v3
Ordering-Inc/Ordering-UI pull request #1303
Opened 2022-09-22 15:21 UTC by mingxue-ordering

Story: https://app.asana.com/0/home/1200550251832815/1202909265940554

2022-09-22 21:46 UTC, carlosq-ordering commented
@mingxue-ordering  You can improve this validation in only one, and you can import it, in order to optimize the code

2022-09-23 08:42 UTC, mingxue-ordering commented
I've add hook to reuse code.

2022-09-23 14:00 UTC, carlosq-ordering requested changes

2022-09-23 14:00 UTC, carlosq-ordering commented on src/themes/five/src/components/SignUpForm/index.js
> +          content: [t('CONFIG_DOENNOT_RECAPTCHA_KEY', 'the config doesn\'t have recaptcha site key')]
Fix typo in lang key

2022-09-23 15:57 UTC, carlosq-ordering approved these changes

2022-09-23 15:57 UTC, merged