[Add] open past orders
Ordering-Inc/Ordering-UI pull request #1486
Opened 2023-01-02 17:50 UTC by Isra1610

story: https://app.asana.com/0/1199511033583011/1203626345903107/f
demo: https://www.loom.com/share/7552798c0ae0421bb5b558dde0527dd3

2023-01-02 18:31 UTC, carlosq-ordering requested changes

2023-01-02 18:31 UTC, carlosq-ordering commented on src/components/VerticalOrdersLayout/SingleOrderCard/index.js
> +  const handleClickCard = (e, order) => {
Please improve this code

2023-01-02 18:50 UTC, Isra1610 commented on src/components/VerticalOrdersLayout/SingleOrderCard/index.js
> +  const handleClickCard = (e, order) => {
done

2023-01-03 19:15 UTC, carlosq-ordering approved these changes

2023-01-03 19:15 UTC, merged