Business map
Ordering-Inc/Ordering-UI pull request #395
Opened 2021-02-03 00:23 UTC by YisusJe

#### Story: https://app.asana.com/0/1191220738645130/1199530338271933

2021-02-03 19:06 UTC, carlosq-ordering requested changes

2021-02-03 19:06 UTC, carlosq-ordering commented on index-template.js
> +    url: 'https://apiv4-dev.ordering.co',
no cambiar

2021-02-03 19:06 UTC, carlosq-ordering commented on template/pages/BusinessesList/index.js
> +      <BusinessesListing {...businessListingProps} externalBusinessMap />
este template no necesita necesita ver este componente

2021-02-03 23:03 UTC, carlosq-ordering commented
Cambiar nombre del componente y aplicar cambios necesarios

2021-02-04 22:46 UTC, carlosq-ordering requested changes

2021-02-04 22:46 UTC, carlosq-ordering commented on src/components/BusinessesListing/index.js
> +  const userLocation = { lat: 40.7751052, lng: -73.9651148 }
Pero por que la hardcodeas? si no se usa el componente nada deberia fallar, y si el componente se va a usar, esa prop debe ser marcada como requerida, no subamos cosas con codigo hardocded porfa

2021-02-04 22:46 UTC, carlosq-ordering commented
Falta el test

2021-02-05 20:35 UTC, quirozcarlos approved these changes

2021-02-05 20:36 UTC, carlosq-ordering approved these changes

2021-02-05 20:36 UTC, merged